### ISSUE TITLE
Release is linked in README but not made

### ISSUE THREAD

**Issue by lenn219** [nikosdion/toggle-dark#1]
I just ran and made sure that it looks good

# download
for most people having to build php is not something that have on their pc's so maybe make a release so there less friction between downloading the software.

# network

if i can ask why are their network request?

**Comment by nikosdion** [comment]
**Download**: Well, this is still not _quite_ ready for prime time. Using it with a CRON job doesn't work. This is a release blocker for me. It _should_ work as per [this merge request](https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/2230) but it doesn't. Perhaps I should try adding `--platform offscreen`.

Even if I build the PHAR archive, you will still need to have PHP installed to run it; PHP doesn't compile to a native binary. I know most people don't use PHP, but that's what I am really good at, so...

Speaking of which, how did you find this repo? I thought I was the only person using this 😅

**Network**: See https://github.com/nikosdion/toggle-dark?tab=readme-ov-file#geography where I explain both why it needs to do an HTTP request, and how to disable network requests altogether. I wrote the network request feature for my laptop which I use when travelling. I use a static longitude and latitude on the desktop, without having to do any network requests.

**Comment by nikosdion** [comment]
It appears that `--platform offscreen` did the trick. There goes the release blocker, so now I published the first release.

**Comment by lenn219** [comment]
"Speaking of which, how did you find this repo? I thought I was the only person using this 😅"

I was looking for a way to automatically change kde's color theme because i really like the way my tablet does it so wanted it on my linux install but cron kinda worked but not really and i tried writing my own script but it didn't work wright so i started looking i found some forums and looked tru git hub and just found it randomly and i know php pretty good so i looked tru the code and it looked fine

thank you for making this

**Comment by nikosdion** [comment]
Awesome! Thank you very much for replying to me, and thank you for reminding me that I meant to complete this but kept forgetting about :)

Have a wonderful day!
